name: transaction_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.0.11
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/app_icon.png
    - assets/images/background.jpg
    - assets/fonts/

  fonts:
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf

flutter_native_splash:
  color: "#ffffff"  # Warna latar belakang splash
  image: assets/images/splash.png  # Gambar yang akan digunakan
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
